version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    versioning-strategy: 'increase'
    ignore:
      - dependency-name: 'postcss-*'
        update-types: ['version-update:semver-major']
      - dependency-name: 'ember-css-modules'
        update-types:
          ['version-update:semver-major', 'version-update:semver-minor']
